# Generated by Django 5.1.1 on 2024-09-14 08:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование категории', max_length=50, verbose_name='наименование')),
                ('description', models.CharField(blank=True, help_text='введите описание категории', max_length=200, null=True, verbose_name='описание')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование продукта', max_length=50, verbose_name='наименование продукта')),
                ('brand', models.CharField(help_text='введите бренд продукта', max_length=50, verbose_name='наименование продукта')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(blank=True, help_text='опишите продукта', max_length=150, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение продукта', null=True, upload_to='products/')),
                ('price', models.IntegerField(help_text='стоимость продукта', verbose_name='стоимость')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='дата создания')),
                ('updated_at', models.DateField(default=datetime.datetime.now, verbose_name='дата редактирования')),
                ('category', models.ForeignKey(help_text='введите название категории', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'category', 'price', 'created_at', 'updated_at'],
            },
        ),
    ]
