# Generated by Django 5.1.1 on 2024-09-14 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите наименование продукта', max_length=50, verbose_name='наименование продукта')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='введите название бренда', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='shop.brand', verbose_name='бренд'),
        ),
    ]
