# Generated by Django 5.1.1 on 2024-09-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_remove_category_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
